-- This file is auto-generated by the migration script
-- for reference purposes only. DO NOT EDIT.

CREATE TABLE fetch_result (
    id INTEGER PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    url TEXT,
    status INT,
    body TEXT
);
CREATE TABLE queue (
    id integer primary key autoincrement,
    created_at timestamp default current_timestamp,
    name text,
    payload text, -- but actually should be json object
    started_at timestamp,
    pid int unique -- ensure only 1 task per process
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_fetch_result_url ON fetch_result(url);
